import React from 'react'
import { Canvas } from '@react-three/fiber'
import { OrbitControls, PerspectiveCamera } from '@react-three/drei'
import Ground from './actors/Ground'
import ASRS from './actors/ASRS'
import MultiShuttle from './actors/MultiShuttle'
import Depallet from './actors/Depallet'
import Palletize from './actors/Palletize'
import Conveyor from './actors/Conveyor'
import AGV from './actors/AGV'
import Flow from './systems/Flow'
export default function Scene(){return (<Canvas shadows camera={{position:[18,14,24],fov:45}}><ambientLight intensity={0.6}/><directionalLight position={[10,20,10]} intensity={1}/><Ground/><ASRS/><MultiShuttle/><Depallet/><Palletize/><Conveyor/><AGV/><Flow/><PerspectiveCamera makeDefault position={[18,14,24]}/><OrbitControls/></Canvas>)}
